Docs/update timelines and add timeline
catenax-eV/catenax-ev.github.io pull request #153
Opened 2024-11-19 15:08 UTC by ther3sa

- Added Timeline 25.06
- Updated Timeline 24.12 and  25.03 to better display Tractus-X meeting
- Added standard timeline in main timeline 
- Made timeline zoomable

2024-11-23 15:03 UTC, stephanbcbauer reviewed
Like the PR, just solved some linting issues. I Also added some suggestions. The idea would be to add headlines on the timelines. It's more structures and the headlines can be used for linking.

Would like this:

<img width="1906" alt="image" src="https://github.com/user-attachments/assets/fa6b2164-7eaf-40ce-a77b-1ae51f70a6e1">
<img width="1904" alt="image" src="https://github.com/user-attachments/assets/64d6b277-afcf-403f-813c-aabc49e50ed1">
<img width="1906" alt="image" src="https://github.com/user-attachments/assets/73de0c8d-ffb2-449d-9e77-6ad1851e29e6">
<img width="1903" alt="image" src="https://github.com/user-attachments/assets/cd006d6c-94d3-4ef3-a742-a3c6d3a3d203">

2024-11-23 15:03 UTC, stephanbcbauer commented on src/pages/timelines.md
>  ## Catena-X Io, incl. Eclipse Tractus-X Release 24.12 & 25.03
```suggestion
### Catena-X Io, incl. Eclipse Tractus-X Release 24.12 & 25.03
```

2024-11-23 15:03 UTC, stephanbcbauer commented on src/pages/timelines.md
> +*Timeline for Release 25.06*
```suggestion

### Catena-X Saturn, incl. Eclipse Tractus-X Release 25.06 & 25.09

[![Timeline for Release 25.06](@site//static/img/cx-timeline-25.06.png)](@site//static/img/cx-timeline-25.06.png)
*Timeline for Release 25.06*
```

2024-11-23 15:03 UTC, stephanbcbauer commented on src/pages/timelines.md
> +*Timeline for Release 25.12*
```suggestion
### Catena-X Titan, incl. Eclipse Tractus-X Release 25.12 & 26.03

[![Timeline for Release 25.12](@site/static/img/cx-timeline-25.12.png)](@site/static/img/cx-timeline-25.12.png)
*Timeline for Release 25.12*
```

2024-11-23 15:03 UTC, stephanbcbauer commented on src/pages/timelines.md
> +*Timeline for Release 25.12*
```suggestion
[![Timeline for Release 25.12](@site/static/img/cx-timeline-25.12.png)](@site/static/img/cx-timeline-25.12.png)
*Timeline for Release 25.12*

:::note
The timeline for Release 26.03 will be published soon.
:::
```

2024-11-24 11:08 UTC, stephanbcbauer commented
BTW I think on the picture we have to look carefully, sometimes the deployment on XX.XX was wrong.

2024-11-24 19:52 UTC, ther3sa commented
> BTW I think on the picture we have to look carefully, sometimes the deployment on XX.XX was wrong.

Thanks for the tip. I'll check it and provide an update :)

2024-11-25 20:44 UTC, stephanbcbauer requested changes
Last change request :)

2024-11-25 20:44 UTC, stephanbcbauer commented on src/pages/release-management.md
> +[![Support Dates](/img/support-dates.jpg)](/img/support-dates.jpg)
Even if /img/... works, you should work with @site/static/img/ to indicate, that the images is really a static image and not in the current folder in an img folder

2024-11-25 20:44 UTC, stephanbcbauer commented on src/pages/release-management.md
> +[![Release Timeline](/img/release-schedule.png)](/img/release-schedule.png)
same here

2024-11-26 12:20 UTC, stephanbcbauer approved these changes
LGTM

2024-11-26 12:20 UTC, merged