Push changes 20240527
catenax-eV/catenax-ev.github.io pull request #39
Opened 2024-05-27 08:42 UTC by Grand-Thibault

2024-05-28 21:28 UTC, jSchuetz88 requested changes
Great work! 
Some of my remarks may require their own issue.
And most of the remarks were just minor typos and/or inconsistencies.

Only two remarks I consider as an issue: 
- the images with a transparent background and black text won't be readable within the dark template (e.g. From Idea to Release Item.drawio.svg ). Please use a white background, so that the images will work in both themes. Images in general should be optimized for the light theme, but also be readable with the dark theme.
- "From Idea to Release Item.drawio.svg" Filenames shouldn't contain whitespaces or upper cases. Plase rename in e.g. "from-idea-to-release-item.drawio.svg" (see kebab-case convention)

2024-05-28 21:28 UTC, jSchuetz88 commented on docs/working-model/02-organizational-structure/overview-roles/catena-x-roles.md
> +The Committee is responsible for assigning tasks to expert groups and providing support and mentoring to ensure their success.
Two points:
 - Is the Committee actually responsible, or able to assign tasks?
 - maybe add something like "*[...] assigning tasks to expert groups within their area / domain of responsibility [...]*"

2024-05-28 21:28 UTC, jSchuetz88 commented on docs/working-model/02-organizational-structure/overview-roles/catena-x-roles.md
> +The focus of the expert group must be on the strategic goal roadmap of Catena-X. The association focuses on implementation and realisation in the expert groups and, via the committee, checks the expe
Most of the times, "committee" was written in upper case. I'm fine with either way, but should by consistent.

2024-05-28 21:28 UTC, jSchuetz88 commented on docs/working-model/02-organizational-structure/overview-roles/catena-x-roles.md
> +Association members can join any expert groups by applying for open seats. The recommended size for expert groups is 5 to 15 core team members. Less core team members might indicated that the topic i
typo: assosciation

2024-05-28 21:28 UTC, jSchuetz88 commented on docs/working-model/02-organizational-structure/overview-roles/catena-x-roles.md
> +Individuals or organizations interested in forming an Expert Group can reach out to the Catena-X Association. The request is then going to be assigned to an committe. The request is then added to the
"Expert group" is mostly written in lower case. Personally I prefer the Upper Case-variant. But it should be consistent.

2024-05-28 21:28 UTC, jSchuetz88 commented on docs/working-model/02-organizational-structure/overview-roles/catena-x-roles.md
> +The committee is going to do a initial validation of the request. If the request is deemed valid, one of the committee members is going to be assigned to the request to serve as the Single Point of C
General suggestion: maybe we should make acronyms used for the first time italic?

``` *Single Point of Contact* (SPOC) ```

-> *Single Point of Contact* (SPOC)

2024-05-28 21:28 UTC, jSchuetz88 commented on docs/working-model/02-organizational-structure/overview-roles/catena-x-roles.md
> +#### Expert group approval
Suggestion: Maybe we need to add a sub-section or information, that expert groups are temporarily and must provide a clear timeline for their task to be achieved.

2024-05-28 21:28 UTC, jSchuetz88 commented on docs/working-model/02-organizational-structure/overview-roles/catena-x-roles.md
> +If a expert group member is stepping down from its position, it can not be handed over to another employee of the same company. The replacement needs to be approved.
approved by whom and how? The Committee? The Expert Group? and as a vote? or decision by the leads?

2024-05-28 21:28 UTC, jSchuetz88 commented on docs/working-model/03-process-from-idea-to-production/03-01-process-from-idea-to-production.md
> +### Refine feature to meet DoE
Please introduce the acronym, as it is used for the first time here.

2024-05-28 21:28 UTC, jSchuetz88 commented on docs/working-model/03-process-from-idea-to-production/03-01-process-from-idea-to-production.md
> +* In **GitHub** we manage the different user journys and related business scenarios as .md files.
typo: -> journys

2024-06-10 08:26 UTC, stephanbcbauer approved these changes
LGTM -> All change requests will be worked in into the private repository by @Grand-Thibault

2024-06-10 08:26 UTC, merged