Update release-notes.md
catenax-eV/catenax-ev.github.io pull request #93
Opened 2024-08-06 20:33 UTC by jSchuetz88

Update final Release Notes for Jupiter.

2024-08-09 06:52 UTC, jSchuetz88 commented
@stephanbcbauer @werner-roman @AnnKaCatX 
I've only updated the standards section of the releases notes. Are there any updates needed for the other sections?

2024-08-09 07:12 UTC, werner-roman commented
Hey @jSchuetz88  - yes the Scope changes of Jupiter and the impact must also be also stated - @theresa is informed she is picking it up

2024-08-15 15:49 UTC, jSchuetz88 commented
@werner-roman @ther3sa 
I added a draft of the "scope clarification" to the release notes. Please review. Maybe more details / information are required regarding CX-0001 and CX-0006?

2024-08-15 15:54 UTC, ther3sa commented
> @werner-roman @ther3sa I added a draft of the "scope clarification" to the release notes. Please review. Maybe more details / information are required regarding CX-0001 and CX-0006?

Should the release note rather go up to the top because of visibility or stay down?

2024-08-15 18:26 UTC, werner-roman requested changes

2024-08-15 18:26 UTC, werner-roman commented on src/pages/release-notes.md
> +To maintain the integrity and reliability of the onboarding process, the signing of self-descriptions (GXDC-compliance check) will be temporarily suspended:
GXDCH 

would write: "the signing of self-descriptions by the Gaia-X Digital Clearing House (GXDCH )will be temporarily suspended:"

2024-08-15 18:26 UTC, werner-roman commented on src/pages/release-notes.md
> +- This suspension only affects the CSP-B role within CX-0001 and CX-0006.
I would link the standards + details wich CAC are affected

2024-08-15 18:34 UTC, werner-roman commented
@jSchuetz88  "AIBSL" is wrong in the standards - it should be "AISBL"

2024-08-16 07:07 UTC, ther3sa approved these changes
Looks good to me

2024-08-16 08:30 UTC, werner-roman approved these changes
LGMT 🚀

2024-08-27 11:22 UTC, stephanbcbauer commented
@jSchuetz88 Should we update the branch here?

2024-09-17 15:37 UTC, merged